language: generic
os: osx
sudo: required 
services:
  - docker

before_install:
  - sudo docker build -t akmaljonsadikov/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true akmaljonsadikov/docker-react npm run test -- --coverage