sudo: required 
language: generic
#node_js:
#  - "8"
os: osx


services:
  - docker

before_install:
  - docker build -t akmaljonsadikov/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true akmaljonsadikov/docker-react npm run test 