language: generic
sudo: required 
services:
  - docker

before_install:
  - docker build -t akmaljonsadikov/docker-react -f Dockerfile.dev .  

script:
  - docker run akmaljonsadikov/docker-react npm run test -- --coverage